Main menu screen +  wave logic
Kinsteen/tower-defense pull request #20
Opened 2023-12-05 20:27 UTC by Kinsteen

Closes #19

2023-12-05 22:42 UTC, PaulLuperini requested changes
Nice work :)

However, having randomness in wave spawns seems weird since it means that waves are not reproducible 🤔

2023-12-05 22:42 UTC, PaulLuperini commented on scenes/PlayMenu.gd
> +	pass
You could remove `_ready` and `_process` as they are not used.

2023-12-05 22:42 UTC, PaulLuperini commented on scenes/GameScene.gd
> +const WAVE_1 = preload("res://resources/Wave1.tres")
Are these variables used? I removed them and saw no issue or difference in gameplay.

2023-12-06 08:57 UTC, Kinsteen commented
Does it matter if waves are not reproducible? I did it just to test stuff, but we could remove it

2023-12-08 21:41 UTC, PaulLuperini commented
No, indeed, it doesn't matter right now. We can remove it at a later stage.

2023-12-09 13:53 UTC, merged